name: Release & Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Specify release type: regular, alpha, beta, or rc'
        required: true
        default: 'regular'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ github.event.inputs.release-type }}

    steps:
      - name: Validate branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Error: This workflow can only be run on the main branch."
            exit 1
          fi

      - name: Validate release type
        run: |
          if [[ "$RELEASE_TYPE" != "regular" && "$RELEASE_TYPE" != "alpha" && "$RELEASE_TYPE" != "beta" && "$RELEASE_TYPE" != "rc" ]]; then
            echo "Error: Invalid release type '$RELEASE_TYPE'. It must be one of: regular, alpha, beta, or rc."
            exit 1
          fi

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Node.js dependencies
        run: npm ci

      - name: Set Git user
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Create settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" \
                  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \
                  xsi:schemaLocation=\"http://www.mavensite.org/xsd/settings-1.0.0.xsd\"> \
                <servers> \
                  <server> \
                    <id>central</id> \
                    <username>${{ secrets.SONATYPE_USERNAME }}</username> \
                    <password>${{ secrets.SONATYPE_PASSWORD }}</password> \
                  </server> \
                </servers> \
                <profiles> \
                  <profile> \
                    <id>central</id> \
                    <activation> \
                      <activeByDefault>true</activeByDefault> \
                    </activation> \
                    <properties> \
                      <gpg.executable>gpg</gpg.executable> \
                      <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase> \
                    </properties> \
                  </profile> \
                </profiles> \
              </settings>" > ~/.m2/settings.xml

      - name: Set up GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "$GPG_PRIVATE_KEY" | gpg --import --batch --yes
          echo -e "5\n" | gpg --batch --yes --pinentry-mode loopback --passphrase "$PASSPHRASE" --command-fd 0 --edit-key "$GPG_KEY_ID" trust quit
          echo -e "trust\n5\ny\nsave\n" | gpg --batch --command-fd 0 --edit-key ${{ secrets.GPG_KEY_ID }}

      - name: Verify GPG key
        run: |
          gpg --list-keys ${{ secrets.GPG_KEY_ID }}

      - name: Run release-it
        run: |
          if [ "$RELEASE_TYPE" == "regular" ]; then
            npx release-it
          else
            npx release-it --preRelease="$RELEASE_TYPE"
          fi
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Print success message
        if: success()
        run: echo "Release and publishing completed successfully!"

      - name: Handle failure
        if: failure()
        run: echo "Release process failed."
