name: Release & Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Specify release type: regular, alpha, beta, or rc'
        required: true
        default: 'regular'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ github.event.inputs.release-type }}

    steps:
      # Check if the workflow is running on the main branch
      - name: Validate branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "Error: This workflow can only be run on the main branch."
            exit 1
          fi

      # Validate the release type
      - name: Validate release type
        run: |
          if [[ "$RELEASE_TYPE" != "regular" && "$RELEASE_TYPE" != "alpha" && "$RELEASE_TYPE" != "beta" && "$RELEASE_TYPE" != "rc" ]]; then
            echo "Error: Invalid release type '$RELEASE_TYPE'. It must be one of: regular, alpha, beta, or rc."
            exit 1
          fi

      # Checkout the code from the repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Setup Java environment
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install Node.js dependencies
      - name: Install Node.js dependencies
        run: npm ci

      # Configure Git user information
      - name: Set Git user
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      # Set up the GPG key for signing
      - name: Set up GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          # Create the GPG directory with secure permissions
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          
          # Import the private key
          echo "$GPG_PRIVATE_KEY" | gpg --import --batch --yes

          # Trust the GPG key (replace <actual_key_id> with your actual key ID)
          gpg --batch --yes --pinentry-mode loopback --passphrase "$PASSPHRASE" --edit-key <actual_key_id> trust quit

      # Run release-it for publishing
      - name: Run release-it
        run: |
          if [ "$RELEASE_TYPE" == "regular" ]; then
            npx release-it
          else
            npx release-it --preRelease="$RELEASE_TYPE"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      # Print a success message if the release was successful
      - name: Print success message
        if: success()
        run: echo "Release and publishing completed successfully!"

      # Print a failure message if the release failed
      - name: Handle failure
        if: failure()
        run: echo "Release process failed."
